[crowsnest]
log_path: ~/printer_data/logs/crowsnest.log
log_level: quiet

[cam 1]
mode: camera-streamer
port: 8080
device: /base/soc/i2c0mux/i2c@1/ov5647@36
resolution: 640x480  # 2026-06-30: CPU負荷低減のため720p->480pに変更
max_fps: 10  # 2026-06-30: CPU負荷低減のため15->10fpsに変更
v4l2ctl:


[cam 2]
mode: camera-streamer                         # または Raspberry Pi 環境であれば camera-streamer
port: 8081                              # cam 1 と重複しないポート
device: /dev/v4l/by-id/usb-UnionImage_Co._Ltd_CCX2F3298_1234567890-video-index0
resolution: 640x480                  # 負荷を抑える場合は 640x480
max_fps: 15                            # 10〜30fps（CPU負荷に応じて調整）
v4l2ctl: power_line_frequency=1,white_balance_automatic=1,auto_exposure=1,brightness=128,contrast=128

